// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoZIqENuke45WTE5m3Hf4R-r3LN4Z5wzU',
    appId: '1:695992616108:web:6441eab7c21f7c46998b09',
    messagingSenderId: '695992616108',
    projectId: 'celulas-app-50668',
    authDomain: 'celulas-app-50668.firebaseapp.com',
    storageBucket: 'celulas-app-50668.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_xJpy9Wim3m7QsAOOtxykf7-mmMdgIuY',
    appId: '1:695992616108:android:2f18287473b7fece998b09',
    messagingSenderId: '695992616108',
    projectId: 'celulas-app-50668',
    storageBucket: 'celulas-app-50668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZOHcz_K_YqLWstX3SbW3Vx5xxT7iLGuw',
    appId: '1:695992616108:ios:99476d95eb094678998b09',
    messagingSenderId: '695992616108',
    projectId: 'celulas-app-50668',
    storageBucket: 'celulas-app-50668.firebasestorage.app',
    iosClientId: '695992616108-mg48o597tb8u6n8r8vijtp0ogdpiku8e.apps.googleusercontent.com',
    iosBundleId: 'com.devhelmont.celulas.celulasApp',
  );
}
